### PR TITLE
Minor changes while looking into MetOffice integration in HassIO

### PR DESCRIPTION
**Pull request by MrHarcombe**
- Correction for minor code transposition in Manager
- Function to return list of non-empty Elements in Timestep seemed borked

### CODE REVIEW

**Comment by MrHarcombe** [comment]
Either way, I'd really love it if you could release a 0.9.6 with the print() statements removed (from Manager) as I'm playing with adding daily forecasts into HomeAssistant, and they really mess the log up :)

**Comment by EJEP** [comment]
Thank you for this, I will try to have a look soon. Regarding removing the print statements, I have plans to replace them with proper logging using python's logging module - would that solve the HomeAssistant log issue?

**Comment by MrHarcombe** [comment]
Absolutely, that would be great!

In fairness, I think the print statements have gone from the latest dev
branch, there's just not been a point release since.

Happy to help 😀

-- Ian

**Comment by EJEP** [comment]
FYI I have just released 0.9.6 which, as you say, has print statements removed

**Pull request merged**
